name: Richard Randak
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      real_name: "Richard"
      pseudo_name: "Thorberg"
      faculty: "FIIT STU"
      home_city: "Bratislava"
      home_state: "Slovakia"